name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "::debug::This is a debug message"
      - uses: actions/checkout@v4
      - name: ha-ha
        uses: ./.github/actions/joke-action
       
